### ISSUE TITLE
iex Financials don't seem to work. 

### ISSUE THREAD

**Issue by neldivad** [TheEliteAnalyst/Riex#4]
```
GM_bs <- iex.balance.sheet("GM", sk)
GM_IS <- iex.income("GM", sk)
GM_CF <- iex.cash.flow("GM", sk)
```
> GM_IS <- iex.income("GM", sk)
[1] "Stock Info is available in IEX"
Error in rjson::fromJSON(url.content) : unexpected character 'T'
> GM_CF <- iex.cash.flow("GM", sk)
[1] "Stock Info is available in IEX"
Error in rjson::fromJSON(url.content) : unexpected character 'T'

Off topic: 
How do you add multiple tickers under one function? 

Example: 
`iex.earnings(c("FB", "AAPL"), sk) `
Does not seem to work. 
>[1] "Stock Info is available in IEX"
Error in rjson::fromJSON(url.content) : unexpected character 'U'
In addition: Warning message:
In if (toupper(x) %in% stocks_list == TRUE) print("Stock Info is available in IEX") else warning("Stock Info is not available in IEX") :
  the condition has length > 1 and only the first element will be used

**Comment by TheEliteAnalyst** [comment]
David,

Thank you for sharing the info about the issue you encountered.. I just
tested it and It  appears the error might be due to the IEX subscription
level.
Can you please check if you have a free subscription?  Issue might also be
due to a bug in "rjson::fromJSON", if this is the case I'll make the
necessary changes and update the package.

As for retrieving data for multiple stocks, I'll include the capability in
next release as well.

Thank you again for the feedback!

Best,
Myriam

[image: image.png]

**Comment by neldivad** [comment]
Yes, I am using a free subscription.

**Comment by TheEliteAnalyst** [comment]
David,

IEX continuously improves the  API and I'm reviewing all functions to
ensure they are current and accurate. In the meantime please forward any
other issues/suggestions you further identify so I can incorporate in
changes.

Thank you!

Best,
Myriam

**Comment by TheEliteAnalyst** [comment]
@neldivad - I'll notify you when the following requested capabilities are added:
-  Adding capability  to generate results for multiple stocks
-  Adding functionality to select sandbox vs subscription based url
Best regards,
Myriam
